- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
    - name: make sure we are running correct Ansible Version
      fail:
        msg: "Ansible version must be at least => 2.3.2"
      when: (ansible_version.major == 1) or
            (ansible_version.major == 2 and ansible_version.minor < 3) or
            (ansible_version.major == 2 and ansible_version.minor == 3 and ansible_version.revision < 2)

    - name: save username of AWS user
      set_fact:
         lightbulb_user: '{{ ec2_key_name }}'

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    teardown: false
  roles:
    - manage_ec2_instances

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  become: yes
  roles:
    - user_accounts
    - common

- name: Configure control node
  hosts: control_nodes
  become: yes
  roles:
    - control_node

- name: Email inventory to students
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - email
