- name: Destroy lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: yes

  vars:
    ec2_exact_count: 0
    teardown: true
    ec2_wait: no

  roles:
    - manage_ec2_instances

  post_tasks:
    - name: Remove inventory files
      file:
        name: "{{ playbook_dir }}/*.txt"
        state: absent
