ec2_name_prefix: TRAINING
ec2_region: us-east-1
ec2_exact_count: 1
ec2_wait: yes
ec2_subnet: "172.16.0.0/16"
ec2_subnet2: "172.17.0.0/16"

ec2_lab_node_types:
  - name: ansible
    type: rhel7-tower

  - name: node1
    type: rhel7

  - name: node2
    type: rhel7

  - name: node3
    type: rhel7

#  - name: haproxy
#    type: rhel7
